#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#

development:
  adapter: mysql
  database: ccx_dev
  username: root
  password:

test:
  adapter: mysql
  database: radiant_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  database: radiant_live
  username: root
  password:
  socket: /tmp/mysql.sock